import fs from "node:fs";
import path from "node:path";

const TEMPLATES_DIR = path.resolve("src/templates");
const OUTPUT_FILE = path.resolve("src/cli/generated/templates.ts");

function walkDir(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

function main() {
  const files = walkDir(TEMPLATES_DIR);
  const result: Record<string, Record<string, string>> = {};

  for (const file of files) {
    const rel = path.relative(TEMPLATES_DIR, file);
    const parts = rel.split(path.sep);
    // category = first two path segments (e.g. "components/combobox") or first segment (e.g. "base")
    let category: string;
    if (parts.length > 2) {
      category = parts.slice(0, 2).join("/");
    } else {
      category = parts[0];
    }
    const filename = parts.length > 2 ? parts.slice(2).join("/") : parts.slice(1).join("/");
    const content = fs.readFileSync(file, "utf-8");

    if (!result[category]) {
      result[category] = {};
    }
    result[category][filename] = content;
  }

  const output = `// Auto-generated by scripts/bundle-templates.ts — do not edit
export const templates: Record<string, Record<string, string>> = ${JSON.stringify(result, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`Bundled ${files.length} template files into ${OUTPUT_FILE}`);
}

main();
