export const componentNav = [
  { label: "Accordion", href: "/components/accordion" },
  { label: "Avatar", href: "/components/avatar" },
  { label: "Carousel", href: "/components/carousel" },
  { label: "Checkbox", href: "/components/checkbox" },
  { label: "Clipboard", href: "/components/clipboard" },
  { label: "Collapsible", href: "/components/collapsible" },
  { label: "ComboBox", href: "/components/combobox" },
  { label: "DatePicker", href: "/components/date-picker" },
  { label: "Dialog", href: "/components/dialog" },
  { label: "FloatingPanel", href: "/components/floating-panel" },
  { label: "Menu", href: "/components/menu" },
  { label: "Password Input", href: "/components/password-input" },
  { label: "Popover", href: "/components/popover" },
  { label: "QrCode", href: "/components/qr-code" },
  { label: "RatingGroup", href: "/components/rating-group" },
  { label: "ScrollArea", href: "/components/scroll-area" },
  { label: "Steps", href: "/components/steps" },
  { label: "Switch", href: "/components/switch" },
  { label: "Tabs", href: "/components/tabs" },
  { label: "TagsInput", href: "/components/tags-input" },
  { label: "Toast", href: "/components/toast" },
  { label: "Toggle", href: "/components/toggle" },
  { label: "Tooltip", href: "/components/tooltip" },
];
