export const componentNav = [
  { label: "Accordion", href: "/components/accordion" },
  { label: "Avatar", href: "/components/avatar" },
  { label: "Carousel", href: "/components/carousel" },
  { label: "Checkbox", href: "/components/checkbox" },
  { label: "Collapsible", href: "/components/collapsible" },
  { label: "ComboBox", href: "/components/combobox" },
  { label: "DatePicker", href: "/components/date-picker" },
  { label: "Dialog", href: "/components/dialog" },
  { label: "Menu", href: "/components/menu" },
  { label: "Switch", href: "/components/switch" },
  { label: "Tabs", href: "/components/tabs" },
  { label: "TagsInput", href: "/components/tags-input" },
  { label: "Toast", href: "/components/toast" },
  { label: "Tooltip", href: "/components/tooltip" },
];
